# Generated by Django 6.0.1 on 2026-03-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rpg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
